export const POST_LOGIN = "POST_LOGIN";
export const SUCCESS_LOGIN = "SUCCESS_LOGIN_ACCESS";
export const FAIL_LOGIN = "FAIL_LOGIN_ACCESS";

export const POST_LOGOUT = "POST_LOGOUT";

export const FETCH_AUTH_INFO = "FETCH_AUTH_INFO";
export const FETCH_AUTH_INFO_FAIL = "FETCH_AUTH_INFO_FAIL";
export const FETCH_AUTH_INFO_SUCCESS = "FETCH_AUTH_INFO_SUCCESS";

export const FETCH_ALL_USERS = "FETCH_ALL_USERS";
export const FETCH_ALL_USERS_FAIL = "FETCH_ALL_USERS_FAIL";
export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS";